// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzyhbgfnbnvkmcdmzzcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6eWhiZ2ZuYm52a21jZG16emNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0OTM2OTUsImV4cCI6MjA4MjA2OTY5NX0.5lJ2MJz-qap--Ituy12tAzzj9_S0QFnzXfC8jcZusVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});